version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-assume-role"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vv3atlnyqj73"
s3_prefix = "aws-assume-role"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
